GET http://{{storagr}}/{{repository}}/objects/batch
Content-Type: application/vnd.git-lfs+json; charset=utf-8
Authorization: Bearer {{token}}

### 

// Download
POST http://{{storagr}}/{{repository}}/objects/batch
Content-Type: application/vnd.git-lfs+json; charset=utf-8
// Authorization: Bearer {{token}
Authorization: Basic {{basic}}

{
  "operation": "download",
  "transfers": [ "basic" ],
  "ref": { "name": "refs/heads/master" },
  "objects": [
    {
      "oid": "{{oid}}",
      "size": {{size}}
    }
  ]
}

###

// Upload
POST http://{{storagr}}/{{repository}}/objects/batch
Content-Type: application/vnd.git-lfs+json; charset=utf-8
// Authorization: Bearer {{token}}
Authorization: Basic {{basic}}

{
  "operation": "upload",
  "transfers": [ "basic" ],
  "ref": { "name": "refs/heads/master" },
  "objects": [
    {
      "oid": "{{oid}}",
      "size": {{size}}
    }
  ]
}