POST http://{{storagr}}/{{repository}}/locks/
Content-Type: application/vnd.git-lfs+json; charset=utf-8
Authorization: Bearer {{token}}

{"path": "jo/yay"}

###

GET http://{{storagr}}/{{repository}}/locks/
Authorization: Bearer {{token}}

###

POST http://{{storagr}}/{{repository}}/locks/verify
Content-Type: application/vnd.git-lfs+json; charset=utf-8
Authorization: Bearer {{token}}

{}

###

POST http://{{storagr}}/{{repository}}/locks/{{lockId}}/unlock
Content-Type: application/vnd.git-lfs+json; charset=utf-8
Authorization: Bearer {{token}}

{"force": false}