// Create Backend User
POST http://{{storagr}}/users/create
Content-Type: application/vnd.git-lfs+json; charset=utf-8

{"username": "{{username}}", "password": "{{password}}", "mail": "test-mail", "roles": ["Admin"]}

###

// List Users
GET http://{{storagr}}/users/
Authorization: Bearer {{token}}

###

// View User
GET http://{{storagr}}/users/{{uid}}
Authorization: Bearer {{token}}